<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_eprivacy"
 *
 * Auto generated by Extension Builder 2020-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'tollwerk ePrivacy Consent Manager',
    'description'      => 'ePrivacy Consent Manager',
    'category'         => 'plugin',
    'author'           => 'Joschi Kuphal',
    'author_email'     => 'joschi@tollwerk.de',
    'state'            => 'alpha',
    'uploadfolder'     => 0,
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '0.1.0',
    'constraints'      => [
        'depends'   => [
            'typo3'   => '6.0.0-7.9.99'
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],
];
